DROP TABLE IF EXISTS clients CASCADE;
DROP SEQUENCE IF EXISTS id_seq CASCADE;

CREATE SEQUENCE id_seq START WITH 6 INCREMENT BY 1;

CREATE TABLE clients (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(50),
	email VARCHAR(50),
	phone VARCHAR(12) ,
	medical_observations VARCHAR(500),
	observations VARCHAR(500)
);
